experiment:
  epochs: 500
  batch_size: 32
  image_size: [224, 224]
  learning_rate: 0.0005
  weight_decay: 0.01
  patience: 50
  min_delta: 1e-4
  task: "classification"  # "classification", "regression", or "multitask"
  state_filter: null  
  models:
    - dla46x_c.in1k
    - mobilenetv3_small_050.lamb_in1k
    - lcnet_050.ra2_in1k
    - mobilenetv2_050.lamb_in1k
    - mnasnet_small.lamb_in1k