# [Data] train_ds=13317 images, valid_ds=2961 images

experiment:
  epochs:         300
  batch_size:     32
  image_size:     [224, 224]
  learning_rate:  5e-5
  weight_decay:   0.05
  patience:       30
  min_delta:      1e-5
  task:           "classification"
  num_classes:    3

  dropout_rate:     0.0
  label_smoothing:  0.0
  mixup_alpha:      0.0
  cutmix_alpha:     0.0
  drop_path_rate:   0.3
  max_norm:         1.0
  replace_large_kernel: false

  train_file_dir: data/csv/train.csv
  valid_file_dir: data/csv/valid.csv
  train_img_dir: D:\Datasets\WithCross Dataset\image
  valid_img_dir: D:\Datasets\WithCross Dataset\image

  AUGMENTATION:
    name: none # none | signalmix
    prob: 0.0
    use_cutmix: false
    cutmix_prob: 0.0
    beta: 1.0
    min_lam: 0.35
    max_lam: 0.65
    protect_radius: 50   
    max_trials: 25        
    signal_dir: D:\Datasets\WithCross Dataset\vidvip_signal/signal
    signal_csv: D:\Datasets\WithCross Dataset\vidvip_signal/signal.csv
    none_index: 0
    transform : simple # simple / albumentation

  LOSS:
    name: "focal"      # "ce" / "weighted_ce" / "focal"
    apply_class_balance: true
    beta: 0.99           
    label_smoothing: 0.0

  models:
    - name: tf_efficientnet_b3.ns_jft_in1k   
      image_size: [300, 300]             
    - name: mobilenetv4_hybrid_medium.e200_r256_in12k_ft_in1k
      image_size: [320, 320]          
    - name: tiny_vit_11m_224.dist_in22k_ft_in1k
      image_size: [224, 224]        
    - name: tf_efficientnet_b2.ns_jft_in1k
      image_size: [260, 260]          
    - name: hgnetv2_b3.ssld_stage2_ft_in1k
      image_size: [288, 288] 
    - name: mobilenetv4_hybrid_medium.ix_e550_r256_in1k
      image_size: [320, 320]             
    - name: tf_efficientnet_b4.ns_jft_in1k
      image_size: [380, 380]          
    - name: hgnetv2_b2.ssld_stage2_ft_in1k
      image_size: [288, 288]        
    - name: tiny_vit_21m_224.dist_in22k_ft_in1k
      image_size: [224, 224]          
                    

