experiment:
  epochs:         500
  batch_size:     32
  image_size:     [224, 224]        
  learning_rate:  0.0001
  weight_decay:   0.5
  patience:       50
  min_delta:      1e-4
  task:           "classification"  # "classification" | "regression" | "multitask"
  state_filter:   null

  models:
    - name: vit_mediumd_patch16_reg4_gap_256.sbb2_e200_in12k_ft_in1k   
      image_size: [256, 256]             
    # - name: tf_efficientnet_b6.ns_jft_in1k
    #   image_size: [528, 528]          
    - name: vit_medium_patch16_gap_256.sw_in12k_ft_in1k
      image_size: [256, 256]        
    - name: convnext_tiny.in12k_ft_in1k
      image_size: [288, 288]          
    - name: edgenext_base.in21k_ft_in1k
      image_size: [288, 288] 
    - name: edgenext_base.usi_in1k   
      image_size: [320, 320]             
    - name: hgnetv2_b4.ssld_stage2_ft_in1k
      image_size: [288, 288]          
    - name: hgnetv2_b3.ssld_stage2_ft_in1k
      image_size: [288, 288]        
    - name: tf_efficientnet_b4.ap_in1k
      image_size: [380, 380]          
    - name: convnext_nano.in12k_ft_in1k
      image_size: [288, 288] 
